language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ctorrent
before_script:
  - composer self-update
  - composer install
script:
  - phpunit --configuration phpunit.xml